...@theme

"root": "this flake" {class: root}
"nixpkgs": "nixpkgs\n56c02bc" {class: flagged}
"nixpkgs_2": "nixpkgs_2\n89570f2" {class: flagged}
"stylix": "stylix" {class: node}
"utils": "utils" {class: node}
"utils_2": "utils_2" {class: node}
"root" -> "nixpkgs" {class: link}
"root" -> "stylix" {class: link}
"root" -> "utils" {class: link}
"stylix" -> "nixpkgs_2": "nixpkgs" {class: link}
"stylix" -> "utils": "systems" {class: follows}
"stylix" -> "utils_2": "utils" {class: link}
