...@theme

"sol": "sol" {class: host}
"hosts/sol/default.nix": "hosts/sol/default.nix" {class: file}
"modules/common.nix": "modules/common.nix" {class: file}
"modules/mesh.nix": "modules/mesh.nix" {
  class: file
  "headscale": "service"
}
"modules/web.nix": "modules/web.nix" {
  class: file
  "nginx": "service"
}
"sol" -> "hosts/sol/default.nix" {class: link}
"hosts/sol/default.nix" -> "modules/common.nix" {class: link}
"hosts/sol/default.nix" -> "modules/mesh.nix" {class: link}
"hosts/sol/default.nix" -> "modules/web.nix" {class: link}
