...@theme

"luna": "luna" {class: host}
"hosts/luna/default.nix": "hosts/luna/default.nix" {
  class: file
  "tailscale": "service"
}
"modules/common.nix": "modules/common.nix" {class: file}
"modules/monitoring.nix": "modules/monitoring.nix" {
  class: file
  "grafana": "service"
}
"luna" -> "hosts/luna/default.nix" {class: link}
"hosts/luna/default.nix" -> "modules/common.nix" {class: link}
"hosts/luna/default.nix" -> "modules/monitoring.nix" {class: link}
