{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.nixdiag.serve;
  apiVersion = "v1";
  dir = "/var/lib/nixdiag/history";
in
{
  options.services.nixdiag.serve = {
    history = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Keep every deployed revision's api/v1/snapshot.json under
        /var/lib/nixdiag/history and serve them at /api/v1/history/.

        This is the one piece of nixdiag that holds mutable state, and it
        has to live here: a derivation is immutable, so it cannot accumulate
        across deploys. It is a oneshot run on activation — no daemon, no
        timer, no database — and nixdiag itself never reads it back.

        Snapshots are filed by revision, so a build with no revision (see
        mkDocs `revision`) is skipped rather than overwriting anything.
      '';
    };
    historyLimit = lib.mkOption {
      type = lib.types.nullOr lib.types.ints.positive;
      default = null;
      example = 200;
      description = ''
        Keep at most this many snapshots, dropping the oldest first. Null
        keeps everything, which is fine until it is not: a long-lived host
        deploying often should set a bound rather than fill /var.
      '';
    };
  };

  config = lib.mkIf (cfg.enable && cfg.history) {
    services.nginx.virtualHosts.${cfg.virtualHost}.locations."/api/${apiVersion}/history/".alias =
      "${dir}/";

    assertions = [
      {
        assertion = cfg.api;
        message = "services.nixdiag.serve.history needs serve.api = true; the snapshots are served under /api/.";
      }
    ];

    systemd.services.nixdiag-history = {
      description = "File this generation's nixdiag snapshot";
      wantedBy = [ "multi-user.target" ];
      before = [ "nginx.service" ];
      path = [
        pkgs.jq
        pkgs.coreutils
        pkgs.findutils
      ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        StateDirectory = "nixdiag/history";
        StateDirectoryMode = "0755";
      };
      script = ''
        set -euo pipefail
        snap=${cfg.docs}/api/${apiVersion}/snapshot.json
        if [ ! -f "$snap" ]; then
          echo "nixdiag: these docs carry no API tree; nothing to file." >&2
          exit 0
        fi
        rev=$(jq -r '.revision.id // empty' "$snap")
        if [ -z "$rev" ]; then
          echo "nixdiag: this build carries no revision; nothing to file." >&2
          exit 0
        fi
        install -m444 "$snap" "$STATE_DIRECTORY/$rev.json"
        ${lib.optionalString (cfg.historyLimit != null) ''
          ls -1t "$STATE_DIRECTORY"/*.json 2>/dev/null \
            | tail -n +${toString (cfg.historyLimit + 1)} \
            | xargs -r rm -f
        ''}
        find "$STATE_DIRECTORY" -maxdepth 1 -name '*.json' ! -name index.json -print0 \
          | sort -z \
          | xargs -0 -r jq -s 'map(.revision) | map(select(. != null))
                 | sort_by(.time) | reverse
                 | { meta: { generator: "Auto-generated by nixdiag. Do not edit.",
                             schema: 1 },
                     revisions: . }' > "$STATE_DIRECTORY/.index.new"
        mv "$STATE_DIRECTORY/.index.new" "$STATE_DIRECTORY/index.json"
      '';
    };
  };
}
