[book]
title = "nixdiag"
description = "Static infrastructure docs from any Nix flake"
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
no-section-label = true
git-repository-url = "https://github.com/kucendro/nixdiag"
site-url = "/nixdiag/"
